### ISSUE TITLE
Добавить страницу про методы str

### ISSUE THREAD

**Issue by hombit** [pykili/pykili.github.io#12]
Часто на семинарах и в ДЗ необходимы те или иные методы класса `str`. Предлагаю сделать отдельную страницу «Строки», например в разделе «О курсе», где перечислить с примерами те методы, что мы часто используем. Также, там можно написать о синтаксисе создания строк (разные кавычки и `r''`) и про операторы `in`, `+`, `*`.

Полный список из 45 методов можно найти [в официальной документации](https://docs.python.org/3/library/stdtypes.html#string-methods). Думаю, что нам хватит дюжины.

В качестве альтернативы можно разместить какую-нибудь хорошую ссылку на русском с примерами.

**Comment by arstotrix** [comment]
я сделаю скелет, если это ещё никто не сделал

**Comment by hombit** [comment]
Изменения в ветке [`str`](https://github.com/pykili/pykili.github.io/tree/str)
